# Generated by Django 5.2.9 on 2026-09-04 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=255)),
                ('seats', models.PositiveIntegerField(help_text='Number of seats available')),
                ('child_seats', models.PositiveIntegerField(help_text='Number of child seats available')),
                ('token_payment_deadline', models.DateTimeField()),
                ('full_payment_deadline', models.DateTimeField()),
                ('token_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('buying_currency', models.CharField(max_length=3)),
                ('buying_price_per_seat_adult', models.DecimalField(decimal_places=2, max_digits=10)),
                ('buying_price_per_seat_child', models.DecimalField(decimal_places=2, max_digits=10)),
                ('buying_price_per_seat_infant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('selling_currency', models.CharField(max_length=3)),
                ('selling_price_per_seat_adult', models.DecimalField(decimal_places=2, max_digits=10)),
                ('selling_price_per_seat_child', models.DecimalField(decimal_places=2, max_digits=10)),
                ('selling_price_per_seat_infant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pnr', models.CharField(max_length=20, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_published', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_number', models.CharField(max_length=20)),
                ('arrival_datetime', models.DateTimeField()),
                ('departure_datetime', models.DateTimeField()),
                ('origin', models.CharField(max_length=3)),
                ('destination', models.CharField(max_length=3)),
                ('operating_airline', models.CharField(max_length=3)),
                ('marketing_airline', models.CharField(max_length=3)),
            ],
            options={
                'db_table': 'segments',
            },
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_number', models.CharField(max_length=20)),
                ('departure_datetime', models.DateTimeField()),
                ('origin', models.CharField(max_length=3)),
                ('arrival_datetime', models.DateTimeField()),
                ('destination', models.CharField(max_length=3)),
                ('travel_class', models.CharField(choices=[('economy', 'Economy'), ('premium_economy', 'Premium Economy'), ('business', 'Business'), ('first', 'First')], default='economy', max_length=20)),
                ('baggage_allowance', models.CharField(max_length=100)),
                ('meal_available', models.BooleanField(default=False)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flights', to='groups_flights.group')),
            ],
            options={
                'db_table': 'flights',
                'constraints': [models.UniqueConstraint(fields=('group', 'flight_number', 'departure_datetime'), name='unique_flight_per_group_departure')],
            },
        ),
    ]
