# Generated by Django 5.2.9 on 2026-09-04 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups_flights', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='flight_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='group',
            name='pnr',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AddConstraint(
            model_name='flight',
            constraint=models.UniqueConstraint(fields=('group', 'flight_number', 'departure_datetime'), name='unique_flight_per_group_departure'),
        ),
    ]
