# Generated by Django 5.2.9 on 2026-09-07 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups_flights', '0002_alter_flight_flight_number_alter_group_pnr_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupBookingDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('on_hold', 'On Hold'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='on_hold', max_length=20)),
                ('requested_adult_seats', models.PositiveIntegerField(default=0)),
                ('requested_child_seats', models.PositiveIntegerField(default=0)),
                ('adult_price_per_seat', models.DecimalField(decimal_places=2, max_digits=10)),
                ('child_price_per_seat', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('token_payment_deadline', models.DateTimeField()),
                ('full_payment_deadline', models.DateTimeField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_details', to='groups_flights.group')),
            ],
            options={
                'db_table': 'group_booking_details',
            },
        ),
    ]
