# Generated by Django 5.2.9 on 2026-09-08 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups_flights', '0006_rename_seats_requested_fields'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='flight',
            name='unique_flight_per_group_departure',
        )
    ]
