# Generated by Django 5.2.9 on 2026-09-11 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups_flights', '0006_rename_seats_requested_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupFlightsInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('financial_profile', models.CharField(max_length=255)),
                ('booking_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='groups_flights.groupbookingdetail')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='groups_flights.group')),
            ],
            options={
                'db_table': 'group_flights_invoices',
            },
        ),
    ]
