# Generated by Django 5.2.9 on 2026-09-15 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups_flights', '0007_groupflightsinvoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupflightsinvoice',
            name='payment_status',
            field=models.CharField(choices=[('token', 'Token Payment'), ('full', 'Full Payment')], default='---', max_length=20),
        ),
    ]
