# Generated by Django 5.2.9 on 2026-09-16 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups_flights', '0008_groupflightsinvoice_payment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupflightsinvoice',
            name='group',
        ),
        migrations.RemoveField(
            model_name='groupflightsinvoice',
            name='status',
        ),
        migrations.AddField(
            model_name='groupflightsinvoice',
            name='invoice_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('posted', 'Posted'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='groupflightsinvoice',
            name='booking_details',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='invoices', to='groups_flights.groupbookingdetail'),
        ),
        migrations.AlterField(
            model_name='groupflightsinvoice',
            name='payment_status',
            field=models.CharField(choices=[('---', '---'), ('token payment', 'Token Payment'), ('full payment', 'Full Payment')], default='---', max_length=20),
        ),
    ]
