# Generated by Django 5.2.9 on 2026-09-16 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups_flights', '0009_remove_groupflightsinvoice_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupflightsinvoice',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='groupflightsinvoice',
            name='financial_profile',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='groupflightsinvoice',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid')], default='unpaid', max_length=20),
        ),
    ]
