# Generated by Django 5.2.9 on 2026-09-16 11:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups_flights', '0010_groupflightsinvoice_date_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupflightsinvoice',
            name='date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
