# Generated by Django 5.2.9 on 2026-09-16 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups_flights', '0011_alter_groupflightsinvoice_date_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupflightsinvoice',
            name='date_time',
        ),
        migrations.AddField(
            model_name='groupflightsinvoice',
            name='payment_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
