# Generated by Django 5.2.9 on 2026-09-08 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups_flights', '0013_remove_flight_unique_flight_per_group_departure_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupbookingdetail',
            name='status',
            field=models.CharField(choices=[('ON_HOLD', 'ON_HOLD'), ('CONFIRMED', 'CONFIRMED'), ('CANCELLED', 'CANCELLED')], default='ON_HOLD', max_length=20),
        ),
    ]
