# Generated by Django 5.2.9 on 2026-09-17 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups_flights', '0018_alter_group_child_seats_defaults'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('alias', models.CharField(blank=True, max_length=100, null=True)),
                ('slug', models.CharField(blank=True, max_length=100, null=True)),
                ('airline_numeric_code', models.CharField(blank=True, default='XYZ', max_length=3, null=True)),
                ('code', models.CharField(max_length=50)),
                ('color', models.CharField(blank=True, max_length=10, null=True)),
                ('has_custom_pricing', models.BooleanField(default=False)),
                ('logo', models.CharField(blank=True, max_length=255, null=True)),
                ('is_enabled', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'airlines',
            },
        ),
        migrations.AlterField(
            model_name='flight',
            name='baggage_allowance',
            field=models.CharField(blank=True, default='20kg', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='adult_seats',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='group',
            name='available_adult_seats',
            field=models.PositiveIntegerField(),
        ),
        migrations.AddField(
            model_name='flight',
            name='airline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flights', to='groups_flights.airline'),
        ),
    ]
