# Generated by Django 5.2.9 on 2026-09-23 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups_flights', '0019_airline_alter_flight_baggage_allowance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='baggage_allowance',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
