# Generated by Django 5.2.9 on 2026-09-02 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupAPIs_AG', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SegmentResearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_number', models.CharField(max_length=20)),
                ('arrival_datetime', models.DateTimeField()),
                ('departure_datetime', models.DateTimeField()),
                ('origin', models.CharField(max_length=3)),
                ('destination', models.CharField(max_length=3)),
                ('operating_airline', models.CharField(max_length=3)),
                ('marketing_airline', models.CharField(max_length=3)),
            ],
        ),
        migrations.RenameModel(
            old_name='group_Flight',
            new_name='Segments',
        ),
    ]
